[package]
name = "vimdir"
version = "0.1.0"
authors = ["Andreas Schärtl <andreas@schaertl.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0.0"
fs_extra = "1.2.0"
git-version = "0.3.4"
structopt = { version = "0.3.21", default-features = false }
tempdir = "0.3.7"